import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <>
      <Head>
          <title>Gabriel R. - Website</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

      <div className={styles.container}>
        <div className={styles.borderGeneral}></div>      
        <aside className={styles.sidebar}>
          <section className={styles.perfil}>
            <a href="/" >
              <Image className={styles.perfilImage} src="/images/gabrielface.jpeg" alt="me" width="75" height="75" />
            </a>
            <h1 className={styles.perfilTitles}>
              Gabriel Ripardo
              <small>
                Front-end Developer
              </small>
            </h1>
            <p className={styles.perfilDescription}>
              Escrevo sobre recursos de 
              linguagens de programação, 
              hacks que facilitam a vida,
              javascript e música. 
            </p>  
          </section>
          <section >
            <nav>
              <ul className={styles.networks}>
                <li className={styles.linkedin}>
                  <a href="https://www.linkedin.com/in/gabriel-sena-317a8412a/">
                    <Image src="/assets/icons/linkedin.svg" alt="linkedin logo" width="25" height="25" />                  
                  </a>
                </li>
                <li className={styles.github}>
                  <a href="https://github.com/gabrielripardo">
                  <Image src="/assets/icons/github.svg" alt="linkedin logo" width="25" height="25" />                  
                  </a>
                </li>
              </ul>
            </nav>
            <nav>
              <ul>
                <li>
                  <a href="">Home</a>
                </li>
                <li>
                  <a href="">Sobre mim</a>
                </li>
                <li>
                  <a href="">Música</a>
                </li>
              </ul> 
            </nav>
          </section>
        </aside>
        <main className={styles.main}>
          <a href="criando-o-efeito-da-chuva-do-matrix-com-javascript-puro" className={styles.postLink}>
            <section className={styles.postContent}>
              <div className={styles.postTag}>
                js
              </div>
              <div className={styles.postBody}>
                <time className={styles.postDate}>
                  20 de dezembro de 2021 
                </time>
                <h1 className={styles.postTitle}>
                  Criando o efeito da chuva do Matrix com JavaScript puro
                </h1>
                <h2 className={styles.postSubtitle}>
                  Aprenda como criar esse efeito em poucas linhas manipulando o Canvas
                </h2>
              </div>
            </section>
          </a>
        </main>
      </div>
      </>
  )
}

export default Home
