import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import apiGithub from './api/github'

const Home: NextPage = () => {
  const curYear = new Date().getFullYear();
  const [repos, setRepos] = useState([]);

  async function getUsers() {
    let url = 'https://api.github.com/users/gabrielripardo/repos';
    try {
        let res = await fetch(url);
        const rep = await res.json();
        setRepos(rep);
        console.log('# repos ',rep);
    } catch (error) {
        console.log(error);
    }
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Gabriel R. - Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Portfólio
        </h1>

        <p className={styles.description}>
          Lista de projetos{' - '}
          <a href="https://github.com/gabrielripardo?tab=repositories">Github</a>
          
        </p>

        <div>
          <p className={styles.description}>
            Projects here         
          {/* <code className={styles.code}>pages/index.tsx</code> */}
          </p>
        </div>             
        <div className={styles.grid}>
          <button onClick={getUsers}>Listar repositório</button>
          {
            repos.map((item: any) => (
              <div>{item.name}</div>
            ))
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
         Gabriel Ripardo | {curYear}
        </a>
      </footer>
    </div>
  )
}

export default Home
